language: rust
sudo: false
dist: trusty

cache:
  cargo: true
  directories:
    - $HOME/.yarn-cache

before_install:
  - nvm install 6.10.0
  - export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH
  - npm config set spin false
  - npm install -g yarn

install:
  - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH
  - yarn
  - yarn run bower install
  - cargo install diesel_cli --debug --no-default-features --features postgres && export PATH=$HOME/.cargo/bin:$PATH
  - cargo install rustfmt
  - rustfmt --version

before_script:
  - diesel database setup

addons:
  postgresql: "9.5"
  apt:
    sources:
      - kalakris-cmake
    packages:
      - cmake
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev

matrix:
  include:
  - rust: stable
    script:
    - cargo fmt -- --write-mode=diff
  - rust: stable
    script:
    - cargo build
    - cargo test
    - yarn run test
  - rust: nightly-2017-03-04
    env: CLIPPY=YESPLEASE
    script:
    - cargo rustc --lib --features "lint" -- -Zno-trans

env:
  global:
    - DATABASE_URL=postgres://postgres:@localhost/cargo_registry_test
    - TEST_DATABASE_URL=postgres://postgres:@localhost/cargo_registry_test

notifications:
  email:
    on_success: never
