language: rust
rust: nightly
sudo: false

before_script:
  - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH
  - psql -c 'create database cargo_registry_test;' -U postgres
  - nvm install 0.12
  - npm install -g phantomjs ember-cli bower
  - npm install
  - bower install

script:
  - cargo build
  - cargo test
  - ember test

after_success:
  - travis-cargo coveralls --no-sudo

addons:
  postgresql: "9.3"
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev

env:
  global:
    - TEST_DATABASE_URL=postgres://postgres:@localhost/cargo_registry_test
    - S3_BUCKET=alexcrichton-test

notifications:
  email:
    on_success: never
