language: rust
rust: stable
sudo: false
dist: trusty

cache:
  directories:
    - $HOME/.yarn-cache

before_install:
  - nvm install 4.6.0
  - export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH
  - npm config set spin false
  - npm install -g yarn

install:
  - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH
  - yarn
  - yarn run bower install

before_script:
  - psql -c 'create database cargo_registry_test;' -U postgres

script:
  - cargo build
  - cargo test
  - yarn run test

after_success:
  - travis-cargo coveralls --no-sudo

addons:
  postgresql: "9.5"
  apt:
    sources:
      - kalakris-cmake
    packages:
      - cmake
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev

env:
  global:
    - TEST_DATABASE_URL=postgres://postgres:@localhost/cargo_registry_test
    - S3_BUCKET=alexcrichton-test

notifications:
  email:
    on_success: never
