language: rust
sudo: false

before_script:
  - psql -c 'create database cargo_registry_test;' -U postgres
  - npm install -g phantomjs ember-cli
  - npm install

script:
  - cargo build
  - cargo test
  - ember test

addons:
  postgresql: "9.3"

env:
  global:
    - TEST_DATABASE_URL=postgres://postgres:@localhost/cargo_registry_test
    - S3_BUCKET=alexcrichton-test

notifications:
  email:
    on_success: never
