language: rust
rust: nightly
sudo: false

cache:
  directories:
    - node_modules

before_install:
  - nvm install 0.12
  - export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH
  - "npm config set spin false"
  - "npm install -g npm@^2"

install:
  - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH
  - npm install -g bower
  - npm install
  - bower install

before_script:
  - psql -c 'create database cargo_registry_test;' -U postgres

script:
  - cargo build
  - cargo test
  - npm test

after_success:
  - travis-cargo coveralls --no-sudo

addons:
  postgresql: "9.3"
  apt:
    sources:
      - kalakris-cmake
    packages:
      - cmake
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev

env:
  global:
    - TEST_DATABASE_URL=postgres://postgres:@localhost/cargo_registry_test
    - S3_BUCKET=alexcrichton-test

notifications:
  email:
    on_success: never
