language: rust
sudo: required
dist: trusty

branches:
  except:
  - staging.tmp

cache:
  cargo: true

addons:
  chrome: stable

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

before_install:
  - nvm install 8

install:
  - cargo install --force diesel_cli --vers 1.0.0-rc1 --debug --no-default-features --features postgres && export PATH=$HOME/.cargo/bin:$PATH

before_script:
  - diesel database setup

addons:
  postgresql: "9.5"
  apt:
    sources:
      - kalakris-cmake
    packages:
      - cmake
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev

matrix:
  fast_finish: true
  allow_failures:
    - rust: nightly
  include:
  - rust: nightly-2017-12-28
    script:
    - cargo install --force rustfmt-nightly --vers 0.3.4
    - cargo fmt -- --write-mode=diff
    - cargo install --force clippy --vers 0.0.177
    - cargo clippy
  - rust: stable
    script:
    - cargo build
    - cargo test
    - npm install
    - npm test
  - rust: beta
    script:
    - cargo build
    - cargo test
  - rust: nightly
    script:
    - cargo build
    - cargo test

env:
  global:
    - DATABASE_URL=postgres://postgres:@localhost/cargo_registry_test
    - TEST_DATABASE_URL=postgres://postgres:@localhost/cargo_registry_test
    - CARGO_TARGET_DIR=target

notifications:
  email:
    on_success: never
