language: rust
sudo: required
dist: trusty

# Ignore this branch per bors-ng documentation
branches:
  except:
    - staging.tmp

cache:
  cargo: true
  directories:
    - $HOME/.npm

env:
  global:
    - JOBS=1 # See https://git.io/vdao3 for details.
    - DATABASE_URL=postgres://postgres:@localhost/cargo_registry_test
    - TEST_DATABASE_URL=postgres://postgres:@localhost/cargo_registry_test
    - CARGO_TARGET_DIR=target
    - PERCY_PARALLEL_TOTAL=2
    # Percy secrets are included here to enable Percy's GitHub integration
    # on community-submitted PRs
    - PERCY_TOKEN=0d8707a02b19aebbec79bb0bf302b8d2fa95edb33169cfe41b084289596670b1
    - PERCY_PROJECT=crates-io/crates.io

install:
  - cargo install --force diesel_cli --vers `cat .diesel_version` --no-default-features --features postgres && export PATH=$HOME/.cargo/bin:$PATH

before_script:
  - diesel database setup

addons:
  chrome: stable
  postgresql: "9.5"
  apt:
    sources:
      - kalakris-cmake
    packages:
      - cmake
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev

matrix:
  fast_finish: true
  allow_failures:
    - rust: nightly
  include:
    - rust: stable
      before_install:
        - nvm install 10
        - rustup component add rustfmt-preview
        - rustup component add clippy-preview
      script:
        - cargo fmt -- --check
        # TODO: Once clippy:: lint syntax is stable, remove everything after the -- below
        - cargo clippy --all-targets -- -A renamed_and_removed_lints
        - cargo build
        - cargo test
        - npm install
        - npm test
    - rust: beta
      script:
        - cargo build
        - cargo test
    - rust: nightly
      script:
        - cargo build
        - cargo test
      # This portion of the cache is quickly invalidated anyway
      before_cache:
        - cargo clean

notifications:
  email:
    on_success: never
