[package]
name = "cargo-registry"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
version = "0.2.2"
license = "MIT OR Apache-2.0"
repository = "https://github.com/rust-lang/crates.io"
description = "Backend of crates.io"

[workspace]

[profile.release]
opt-level = 2

[lib]
name = "cargo_registry"
doctest = false

[[test]]
name = "all"
path = "src/tests/all.rs"

[package.metadata.docs.rs]
rustdoc-args = [
    "--no-defaults",
    "--passes", "collapse-docs",
    "--passes", "unindent-comments"
]

[dependencies]
cargo-registry-s3 = { path = "src/s3", version = "0.2.0" }
rand = "0.3"
git2 = "0.6.4"
flate2 = "1.0"
semver = "0.5"
url = "1.2.1"
tar = "0.4.13"

openssl = "0.9.14"
curl = "0.4"
oauth2 = "0.3"
log = "0.3"
env_logger = "0.5"
hex = "0.3"
htmlescape = "0.3.1"
license-exprs = "^1.4"
dotenv = "0.11.0"
toml = "0.4"
diesel = { version = "1.3.0", features = ["postgres", "serde_json", "chrono", "r2d2"] }
diesel_full_text_search = "1.0.0"
serde_json = "1.0.0"
serde_derive = "1.0.0"
serde = "1.0.0"
chrono = { version = "0.4.0", features = ["serde"] }
comrak = { version = "0.2.3", default-features = false }
ammonia = "1.0.0"
docopt = "0.8.1"
itertools = "0.6.0"
scheduled-thread-pool = "0.2.0"
derive_deref = "1.0.0"

lettre = "0.8"
lettre_email = "0.8"

conduit = "0.8"
conduit-conditional-get = "0.8"
conduit-cookie = "0.8"
cookie = "0.9"
conduit-middleware = "0.8"
conduit-router = "0.8"
conduit-static = "0.8"
conduit-git-http-backend = "0.8"
conduit-hyper = "0.1"

[dev-dependencies]
conduit-test = "0.8"
hyper = "0.12"
hyper-tls = "0.2"
futures = "0.1"
tokio-core = "0.1"
tokio-service = "0.1"

[build-dependencies]
dotenv = "0.11"
diesel = { version = "1.3.0", features = ["postgres"] }
diesel_migrations = { version = "1.3.0", features = ["postgres"] }

# Remove once cookie depends on ring >= 0.13.0
[patch.crates-io]
ring = { git = "https://github.com/SergioBenitez/ring", branch = "v0.11" }
