[project]
name = "cargo-registry"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
version = "0.1.0"

[profile.dev]
debug = false

[lib]
name = "cargo-registry"
test = false
doctest = false

[[bin]]
name = "server"
test = false

[[bin]]
name = "migrate"
test = false

[[bin]]
name = "update-downloads"

[[bin]]
name = "delete-crate"
test = false

[[bin]]
name = "delete-version"
test = false

[[bin]]
name = "populate"
test = false

[[test]]
name = "all"
path = "src/tests/all.rs"

[dependencies]
rand = "0.1"
time = "0.1.3"
git2 = "0.1.0"
flate2 = "0.1.0"
semver = "0.1.3"
url = "0.2.0"
r2d2 = "0.4.0"
r2d2_postgres = "0.5.0"
openssl = "0.3.0"
postgres = "0.5"
curl = "0.1.0"
oauth2 = "0.1.0"
log = "0.2"
env_logger = "0.2"
rustc-serialize = "0.2"

conduit = "0.6"
conduit-conditional-get = "0.6"
conduit-cookie = "0.6"
conduit-json-parser = "0.6"
conduit-log-requests = "0.6"
conduit-middleware = "0.6"
conduit-router = "0.6"
conduit-static = "0.6"
civet = "0.1.0"

[dependencies.s3]
path = "src/s3"

[dependencies.migrate]
path = "src/migrate"

[dev-dependencies]
conduit-test = "0.6"

