[project]
name = "cargo-registry"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
version = "0.1.0"

[profile.release]
opt-level = 2

[lib]
name = "cargo_registry"
doctest = false

[[test]]
name = "all"
path = "src/tests/all.rs"

[dependencies]
s3 = { path = "src/s3" }
migrate = { path = "src/migrate" }
rand = "0.3"
time = "0.1"
git2 = "0.6.4"
flate2 = "0.2"
semver = "0.5"
url = "1.2.1"
postgres = { version = "0.13", features = ["with-time", "with-openssl", "with-rustc-serialize"] }
r2d2 = "0.7.0"
r2d2_postgres = "0.11"
openssl = "0.9"
curl = "0.4"
oauth2 = "0.3"
log = "0.3"
env_logger = "0.4"
rustc-serialize = "0.3"
license-exprs = "^1.3"
dotenv = "0.8.0"
toml = "0.2"

conduit = "0.8"
conduit-conditional-get = "0.8"
conduit-cookie = "0.8"
conduit-json-parser = "0.8"
conduit-log-requests = "0.8"
conduit-middleware = "0.8"
conduit-router = "0.8"
conduit-static = "0.8"
conduit-git-http-backend = "0.8"
civet = "0.9"


[dev-dependencies]
conduit-test = "0.8"
bufstream = "0.1"

[features]
unstable = []
