[development-tools]
name = "Development Tools"
description = "Ways to make developing in Rust better"

  [development-tools.categories.testing]
  name = "Testing"
  description = "Additions to automated testing features"

    [development-tools.categories.testing.categories.mocking]
    name = "Mocking"
    description = "Mocks are not the same as stubs!"

[libraries]
name = "Libraries"
description = "Libraries are reusable pieces of code"

  [libraries.categories.async]
  name = "Async"
  description = "Code that can take time to run but won't block"

  [libraries.categories.date-and-time]
  name = "Date and Time"
  description = "Date and time math"

[games]
name = "Games"
description = "Share fun things"
